### ISSUE TITLE
Allow to leave an empty description, or at least not cancel the current documentation operation if it occur

### ISSUE THREAD

**Issue by giovannetti-eric** [Cloud-Officer/soup#30]
I should have the ability to skip questions so I can fill them out myself if needed later without the script canceling all the current documentation operation.

Example:

I have multiple packages related to Fontawesome.
The requirement and verification reasoning is the same for each of them.
It's very tedious to enter the same information over and over again.

So I decided not to fill in the fields for the following packages and to copy/paste them myself by hand at the end of the process.

However, when I left a verification reasoning field empty, an error message telling me that it is mandatory appeared, and the script stopped... and I had to start from the beginning again for all of my descriptions...

**Comment by ydesgagn** [comment]
You can use the `--auto_reply` parameter for that.
