### ISSUE TITLE
Some packages asked for are not in the package.json.

### ISSUE THREAD

**Issue by giovannetti-eric** [Cloud-Officer/soup#32]
Using npm.

Sometime, it ask for some packages with 2 letters that are not present in the package.json like **Enter risk level for package he**.

**Comment by ydesgagn** [comment]
It's the name used in the npm registry. Entries like that for sub-packages

`
   "node_modules/webpack-bundle-analyzer/node_modules/ws": {
      "version": "7.5.9",
      "resolved": "https://registry.npmjs.org/ws/-/ws-7.5.9.tgz",
      "integrity": "sha512-F+P9Jil7UiSKSkppIiD94dN07AwvFixvLIj1Og1Rl9GGMuNipJnV9JzjD6XuqmAeiswGvUmNLjr5cFuXwNS77Q==",
      "dev": true,
      "engines": {
        "node": ">=8.3.0"
      },
`

Would be listed as `ws` only and not under the full `webpack-bundle-analyzer/node_modules/ws`.
